const RECIPE_ACTIONS = {
    ACTION_RECIPES_REQUEST: 'ACTION_RECIPES_REQUEST',
    ACTION_RECIPES_FAILURE: 'ACTION_RECIPES_FAILURE',
    ADD_RECIPE_SUCCESS: 'ADD_RECIPE_SUCCESS',
    FETCH_ALL_RECIPES_SUCCESS: 'FETCH_ALL_RECIPES_SUCCESS',
    FETCH_A_RECIPE_SUCCESS: 'FETCH_A_RECIPE_SUCCESS',
    UPDATE_RECIPE_SUCCESS: 'UPDATE_RECIPE_SUCCESS',
    DELETE_RECIPE_SUCCESS: 'DELETE_RECIPE_SUCCESS',
    CLEAR_RECIPE_SUCCESS: 'CLEAR_RECIPE_SUCCESS',
    FETCH_RECIPE_ID_SUCCESS: 'FETCH_RECIPE_ID_SUCCESS',
}

export default RECIPE_ACTIONS