const RECIPE_ACTIONS = {
    ADD_RECIPE: 'ADD_RECIPE',
    UPDATE_RECIPE: 'UPDATE_RECIPE',
    REMOVE_RECIPE: 'REMOVE_RECIPE',
    EMPTY_RECIPE: 'EMPTY_RECIPE',
    FETCH_RECIPE_REQUEST: 'FETCH_RECIPE_REQUEST',
    FETCH_RECIPE_SUCCESS: 'FETCH_RECIPE_SUCCESS',
    FETCH_RECIPE_FAILURE: 'FETCH_RECIPE_FAILURE',

}

export default RECIPE_ACTIONS