const DIET_ACTIONS = {
    ADD_DIET_REQUEST: 'ADD_DIET_REQUEST',
    ADD_DIET_SUCCESS: 'ADD_DIET_SUCCESS',
    ADD_DIET_FAILURE: 'ADD_DIET_FAILURE',

    FETCH_ALL_DIETS_REQUEST: 'FETCH_ALL_DIETS_REQUEST',
    FETCH_ALL_DIETS_SUCCESS: 'FETCH_ALL_DIETS_SUCCESS',
    FETCH_ALL_DIETS_FAILURE: 'FETCH_ALL_DIETS_FAILURE',

    FETCH_A_DIET_REQUEST: 'FETCH_A_DIET_REQUEST',
    FETCH_A_DIET_SUCCESS: 'FETCH_A_DIET_SUCCESS',
    FETCH_A_DIET_FAILURE: 'FETCH_A_DIET_FAILURE',

    UPDATE_DIET_REQUEST: 'UPDATE_DIET_REQUEST',
    UPDATE_DIET_SUCCESS: 'UPDATE_DIET_SUCCESS',
    UPDATE_DIET_FAILURE: 'UPDATE_DIET_FAILURE',

    DELETE_DIET_REQUEST: 'DELETE_DIET_REQUEST',
    DELETE_DIET_SUCCESS: 'DELETE_DIET_SUCCESS',
    DELETE_DIET_FAILURE: 'DELETE_DIET_FAILURE',

}

export default DIET_ACTIONS