const CART_ACTIONS = {
    ADD_TO_CART: 'ADD_TO_CART',
    UPDATE_TO_CART: 'UPDATE_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    EMPTY_CART: 'EMPTY_CART',
    CHECKOUT_REQUEST: 'CHECKOUT_REQUEST',
    CHECKOUT_SUCCESS: 'CHECKOUT_SUCCESS',
    CHECKOUT_FAILURE: 'CHECKOUT_FAILURE'
}

export default CART_ACTIONS